branch-defaults:
  master:
    environment: ChildSafeMask-env
environment-defaults:
  ChildSafeMask-env:
    branch: null
    repository: null
global:
  application_name: child-safe-mask
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Python 3.7 running
    on 64bit Amazon Linux 2/3.1.3
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: liam-personal
  sc: git
  workspace_type: Application
